# -*- coding: utf-8 -*-
"""Copy of calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFjob9s9YOkEOi96We2-5ZkIFfnmH9Mz

calculator.by
"""

def add(x, y):
    return x + y


def subtract(x, y):
    return x - y


def multiply(x, y):
    return x * y


def divide(x, y):
    if y == 0:
      return "error. can't divide by zero"
    return x /y


def square(x):
    return x **2


def power(x, y):
    return x **y


def sqrt(x):
    return x **0.5